name = "clawd-reflections"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[env.production]
routes = [
  { pattern = "reflections.sourcebottle.dev", custom_domain = true }
]
